windows:
  - name: sample-three-panes
  - root: ~
    pre: cwd=$(pwd)
    layout: main-vertical
    panes:
      - name: 'docker-compose'
        commands:
          - just test/watch
        # - just down
        # - just build
        # - just up
        # - lzd
      - name: 'watch'
        commands:
        - just watch
      - name: 'git'
        commands:
        - git status
      