services:
  - docker

sudo: required

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

git:
    submodules: false

env:
  - DOCKER_COMPOSE_VERSION: 1.8.0

script:
  - make travis
