steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "TEST/BUILD"
    docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA --target prod --build-arg TAG=$SHORT_SHA .
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "PUSH"
    if [[ "$BRANCH_NAME" != "master" ]]; then echo "Not master, not pushing"; exit 0; fi;
    docker push gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
