steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '--target', 'prod', '--build-arg', 'TAG=$SHORT_SHA', '.' ]
# images: [ 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA' ]
