# secrets:
# - kmsKeyName: projects/t9-docker-images/locations/global/keyRings/t9_cloud_build/cryptoKeys/cloud_build_key_github_token
#   secretEnv:
#     NPM_TOKEN: |
#       CiQAiVVX3HIaDHpLvVt7XXSDfeq9UtIyLKE3f9ogYEAB3uOoFgcSUQDvWY1ru+vRYEvL6oufZzcl
#       CnXDWKHO3Bfhos0UAOkqFxA0PgWVYq6bpWPh/O8xQrFJf/finV4qAa6c+U1aqUroYiVJ+Uer2cpT
#       Z+AzBq5rHg==

steps:

# Ensure that the builder image exists, if not, build it
# The builder image has all tools and dependencies required to build
# the final artifact(s)
- name: 'docker/compose:1.22.0'
  id: 'builder'
  env:
  - 'DOCKER_REPOSITORY=gcr.io/t9-docker-images/$REPO_NAME'
  - 'BUILDER_DOCKER_COMPOSE=docker-compose.yml'
  # "builder" is the docker image target used for all further operations
  # It is renamed to the branch name for later steps
  - 'BUILDER_DOCKERFILE_TARGET=builder'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      DOCKER_REPOSITORY=$$DOCKER_REPOSITORY docker-compose -f $$BUILDER_DOCKER_COMPOSE pull --ignore-pull-failures --include-deps $$BUILDER_DOCKERFILE_TARGET
      DOCKER_REPOSITORY=$$DOCKER_REPOSITORY docker-compose -f $$BUILDER_DOCKER_COMPOSE build $$BUILDER_DOCKERFILE_TARGET
      DOCKER_REPOSITORY=$$DOCKER_REPOSITORY docker-compose -f $$BUILDER_DOCKER_COMPOSE push $$BUILDER_DOCKERFILE_TARGET
      docker tag $$DOCKER_REPOSITORY:$$BUILDER_DOCKERFILE_TARGET $$DOCKER_REPOSITORY:$BRANCH_NAME

- name: 'gcr.io/t9-docker-images/$REPO_NAME:$BRANCH_NAME'
  id: 'build'
  env:
  - 'DOCKER_REGISTRY=gcr.io/t9-docker-images'
  - 'DOCKER_TAG=$COMMIT_SHA'
  - 'PROJECT_NAME=$REPO_NAME'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      make ci-pull
      make ci-build
      make ci-push-builder

- name: 'gcr.io/t9-docker-images/$REPO_NAME:$BRANCH_NAME'
  id: 'test'
  env:
  - 'DOCKER_REGISTRY=gcr.io/t9-docker-images'
  - 'DOCKER_TAG=$COMMIT_SHA'
  - 'PROJECT_NAME=$REPO_NAME'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      if [[ "$BRANCH_NAME" == "master" ]]; then echo "Master, not testing"; exit 0; fi;
      echo "Tests go here"

- name: 'gcr.io/t9-docker-images/$REPO_NAME:$BRANCH_NAME'
  id: 'deploy'
  # secretEnv: ['NPM_TOKEN']
  env:
  - 'DOCKER_REGISTRY=gcr.io/t9-docker-images'
  - 'DOCKER_TAG=$COMMIT_SHA'
  - 'PROJECT_NAME=$REPO_NAME'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "deploy goes here"
