steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "TEST"
    if [[ "$BRANCH_NAME" == "master" ]]; then exit 0; fi; docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA --target prod --build-arg TAG=$SHORT_SHA .
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "BUILD"
    if [[ "$BRANCH_NAME" != "master" ]]; then echo "Not master, not building"; exit 0; fi; docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA --target prod --build-arg TAG=$SHORT_SHA .
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "PUSH"
    docker push gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
