version: '2.3'

services:
  build:
    volumes:
     # We need to mount all this shit because node_modules must be in the project root
      - ./build:/workspace/build
      - ./docs:/workspace/docs
      - ./etc:/workspace/etc
      - ./src:/workspace/src
      - ./build-base.hxml:/workspace/build-base.hxml
      - ./build-metaframe.hxml:/workspace/build-metaframe.hxml
      - ./build-metapage.hxml:/workspace/build-metapage.hxml
      - ./webpack.config.js:/workspace/webpack.config.js

  test:
    command: ["/bin/sh", "-c", "nodemon --watch docs/js test/test.js"]
    volumes:
      - ./docs:/workspace/docs
      - ./etc:/workspace/etc
      - ./test:/workspace/test

  jekyll:
    volumes:
      - ./docs:/srv/jekyll:cached
