version: '2.3'

services:

  builder:
    image: ${DOCKER_REPOSITORY}:builder
    build:
      context: .
      target: builder
      cache_from:
        - ${DOCKER_REPOSITORY}:builder

  # haxe:
  #   image: ${DOCKER_REPOSITORY}:haxe
  #   build:
  #     context: .
  #     target: haxe
  #     args:
  #       - DOCKER_TAG=${DOCKER_TAG:-latest}
  #     cache_from:
  #       - ${DOCKER_REPOSITORY}:builder
  #       - ${DOCKER_REPOSITORY}:haxe
