version: '2.3'

services:
  builder-haxe:
    command: just watch
    volumes:
     - ./docs:/docs
     - ./libs:/workspace

  test:
    command: ["/bin/sh", "-c", "nodemon --watch /docs/js --watch test test/test.js"]
    volumes:
      - ./docs:/docs
      - ./libs/etc:/workspace/etc
      - ./libs/test:/workspace/test

  jekyll:
    volumes:
      - ./docs:/srv/jekyll
