version: '2.3'

services:

  builder:
    image: ${DOCKER_REPOSITORY}:builder
    build:
      context: .
      target: builder
      cache_from:
        - ${DOCKER_REPOSITORY}:builder

  haxe:
    image: ${DOCKER_REPOSITORY}:haxe
    build:
      context: .
      target: haxe
      cache_from:
        - ${DOCKER_REPOSITORY}:builder
        - ${DOCKER_REPOSITORY}:haxe

  jekyll:
    image: ${DOCKER_REPOSITORY}:jekyll
    build:
      context: .
      target: jekyll
      cache_from:
        - ${DOCKER_REPOSITORY}:builder
        - ${DOCKER_REPOSITORY}:haxe
        - ${DOCKER_REPOSITORY}:jekyll
    command: jekyll serve --watch --force_polling --config _config.yml,_config.dev.yml
    ports:
      - "4000:${PORT_METAPAGE:-4000}"
    volumes:
      - ./docs:/srv/jekyll

  dev:
    depends_on:
      - builder
    build:
      context: .
      target: builder
      cache_from:
        - ${DOCKER_REPOSITORY}:builder
    command: haxelib install build.hxml && haxe build.hxml
    volumes:
      - ./:/app
