version: '2'

services:

  metapagewebsite:
    build: ../metapage/docs
    command: ['jekyll', 'serve', '--watch', '--force_polling', '--config', '_config.yml,_config.dev.yml']
    ports:
      - "4000:4000"
    volumes:
      - ../metapage/docs:/srv/jekyll
    networks:
      - mps
  haxe:
    image: "haxe:3.4"
    volumes:
      - ./:/app
    working_dir: /app
    command: ["haxe", "build.hxml"]

  # Installs haxelibs locally
  haxelibs:
    image: dionjwa/haxe-watch:v0.15.0
    command: ["/bin/sh", "-c", 'haxelib install --always build.hxml']
    working_dir: /app
    volumes:
      - ./.haxelib:/app/.haxelib
      - ./src:/app/src

  # Simply installs npm modules into a persistent docker volume
  # for efficiency. Used by reloaders, not the main app
  node_modules:
    image: dionjwa/haxe-watch:v0.15.0
    working_dir: /app
    command: ["/bin/sh", "-c", "npm i"]
    volumes:
      - ./node_modules_docker:/app/node_modules
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json

  #Build all
  compile:
    image: dionjwa/haxe-watch:v0.15.0
    command: ["sh", "-c", "haxe build.hxml"]
    working_dir: /app
    volumes:
      - ./:/app
