version: '2.3'

networks:
  bridge:
    driver: bridge

services:

  shell:
    image: gcr.io/t9-docker-images/metapage:shell
    build:
      context: .
      target: shell
      cache_from:
        - gcr.io/t9-docker-images/metapage:shell
    networks:
      - bridge

  shell-haxe:
    image: gcr.io/t9-docker-images/metapage:shell-haxe
    build:
      context: ./libs
      target: shell-haxe
      cache_from:
        - gcr.io/t9-docker-images/metapage:shell
        - gcr.io/t9-docker-images/metapage:shell-haxe

  test:
    depends_on:
      jekyll:
        condition: service_healthy
    build:
      context: ./libs
      target: test
      cache_from:
        - gcr.io/t9-docker-images/metapage:shell
        - gcr.io/t9-docker-images/metapage:shell-haxe
    command: ["/bin/sh", "-c", "node test/test.js"]
    networks:
      - bridge

  jekyll:
    image: gcr.io/t9-docker-images/metapage:jekyll
    build:
      context: ./docs
      args:
        JEKYLL_GITHUB_TOKEN: ${JEKYLL_GITHUB_TOKEN}
      cache_from:
        - gcr.io/t9-docker-images/metapage:jekyll
    command: jekyll serve --watch --force_polling --config _config.dev.yml
    ports:
      - "4000:${PORT_METAPAGE:-4000}"
    networks:
      - bridge
    environment:
     - "JEKYLL_GITHUB_TOKEN=${JEKYLL_GITHUB_TOKEN}"
     - "JEKYLL_ENV=development"

