version: '2.3'

services:
  shell-haxe:
    command: just watch
    environment:
     - "NODE_ENV=development"
    volumes:
      - ./docs:/docs
      - ./libs/build:/workspace/build
      - ./libs/etc:/workspace/etc
      - ./libs/ts:/workspace/ts
      - ./libs/test:/workspace/test
      - ./libs/build-base.hxml:/workspace/build-base.hxml
      - ./libs/build-metaframe.hxml:/workspace/build-metaframe.hxml
      - ./libs/build-metapage.hxml:/workspace/build-metapage.hxml
      - ./libs/build.hxml:/workspace/build.hxml
      - ./libs/haxelib.json:/workspace/haxelib.json
      - ./libs/justfile:/workspace/justfile
      - ./libs/package.json:/workspace/package.json
      - ./libs/package-lock.json:/workspace/package-lock.json
      # For simulating ci
      - /var/run/docker.sock:/var/run/docker.sock

  test:
    command: ["/bin/sh", "-c", "nodemon --legacy-watch -e js,md --watch /docs/js --watch test --watch /docs/_metapages/test --watch /docs/_metaframes/test test/test.js"]
    volumes:
      - ./docs:/docs
      - ./libs/etc:/workspace/etc
      - ./libs/test:/workspace/test

  docs:
    command: jekyll serve --watch --force_polling --config _config.yml,_config.dev.yml
    volumes:
      - ./docs:/workspace

