version: '2.3'

services:
  builder-haxe:
    command: just watch
    volumes:
      - ./docs:/docs
      - ./libs:/workspace
      # For simulating ci
      - /var/run/docker.sock:/var/run/docker.sock

  test:
    command: ["/bin/sh", "-c", "nodemon --legacy-watch -e js,md --watch /docs/js --watch test --watch /docs/_metapages/test --watch /docs/_metaframes/test test/test.js"]
    volumes:
      - ./docs:/docs
      - ./libs/etc:/workspace/etc
      - ./libs/test:/workspace/test

  jekyll:
    volumes:
      - ./docs:/workspace

  # By prepending any external urls with http://localhost:3000
  # e.g. http://localhost:3000/https://app.metapages.org/
  # we can transparently proxy metapages so they are all http
  # and cors won't break everything
  # If you change PORT_PROXY you'll need set the same port change in app-metapage-local
  proxy:
    image: imjacobclark/cors-container
    ports:
      - "3000:${PORT_PROXY:-3000}"
    networks:
      - bridge
