version: '2'

services:

  jekyll:
    build: ./docs
    command: ['jekyll', 'serve', '--watch', '--force_polling', '--config', '_config.yml,_config.dev.yml']
    ports:
      - "4000:${PORT_METAPAGE:-4000}"
    volumes:
      - ./docs:/srv/jekyll
