version: '2'

services:

  # Installs haxelibs locally
  haxelibs:
    image: dionjwa/haxe-watch:v0.15.0
    command: ["/bin/sh", "-c", 'haxelib newrepo && haxelib install --always build.hxml']
    working_dir: /app
    volumes:
      - ./:/app

  #Build all
  compile:
    image: dionjwa/haxe-watch:v0.15.0
    command: ["sh", "-c", "haxe build.hxml"]
    working_dir: /app
    volumes:
      - ./:/app
