# https://jekyllrb.com/docs/configuration/options/
#Controls logic for changing asset urls
environment: testing
baseurl: "/docs"
url: "https://metapage-npm.dev:4440"

jekyll_tidy:
  exclude: ["README.md"]
  # I don't know what this line means
  # ignore_env: development
  compress_html: false
