# Template docker-compose application

version: "2.4"

services:

  libs:
    # x-publish consumed by cloudseed
    x-publish: true
    image: ${DOCKER_REGISTRY}${DOCKER_IMAGE_PREFIX}libs:${DOCKER_TAG:-cache}
    build:
      context: ./libs
      target: build
    command: just test
    environment:
      - "NPM_TOKEN=${NPM_TOKEN:-}"
    networks:
      - default

  docs:
    # x-publish consumed by cloudseed
    x-publish: true
    image: ${DOCKER_REGISTRY}${DOCKER_IMAGE_PREFIX}docs:${DOCKER_TAG:-cache}
    build:
      context: ./docs
      args:
        JEKYLL_GITHUB_TOKEN: ${JEKYLL_GITHUB_TOKEN}
        DOCKER_TAG: ${DOCKER_TAG:-cache}
        DOCKER_REGISTRY: ${DOCKER_REGISTRY:-}
        DOCKER_IMAGE_PREFIX: ${DOCKER_IMAGE_PREFIX:-}
    command: jekyll build --config _config.yml
    environment:
     - "JEKYLL_GITHUB_TOKEN=${JEKYLL_GITHUB_TOKEN}"
     - "JEKYLL_ENV=production"
    networks:
      - default


networks:
  default:
    driver: bridge
