#Site settings
source: ./
title: Metapages
# url: "https://dionjwa.github.io" # the base hostname & protocol for your site
baseurl: /metapage
# github:
#   repository_nwo: /amagod/metapage

github_username:  dionjwa
# site.github.url: https://pages.git.com/amagod/metapage

# Build settings
markdown: kramdown
theme: minima
include: ['docs/pages']
collections:
  metaframes:
    output: true
  metapages:
    output: true
  tools:
    output: true
