#Site settings
source: ./
title: Metapages
baseurl: ""

# Build settings
markdown: kramdown
theme: minima

include: ['pages']
collections:
  metaframes:
    output: true
  metapages:
    output: true
  tools:
    output: true

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
