# THIS IS A DUPLICATE OF THE _config.yml FILE
# STUPID JEKYLL DOESN'T MERGE NULLS SO I CANNOT
# DISABLE THE REMOTE THEME LOCALLY IT'S FORKING SLOW

#Controls logic for changing asset urls
environment: development

#Site settings
source: ./
title: Metapages
# description: A short description of your site's purpose
baseurl: ""
repository: metapages/metapage

include: ['pages']
collections:
  metaframes:
    output: true
  metapages:
    output: true
  tools:
    output: true
  plugins:
    output: true
  versions:
    output: true

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

# Build settings
markdown: kramdown
# How to change themes: https://jekyllrb.com/docs/themes/
plugins:
  - jekyll-remote-theme
theme: just-the-docs

# search_enabled: false
# remote_theme: null

# Aux links for the upper right navigation
aux_links:
    "GitHub":
      - "//github.com/metapages/metapage"
    "npm":
      - "//www.npmjs.com/package/metapage"
    "Metapage Viewer":
      - "//app.metapages.org/"
