version: '2'

services:

  jekyll-container:
    build: .
    # image: "jekyll/jekyll:latest"
    # command: ['jekyll', 'serve', '--watch', '--force_polling', '--config', '_config.yml,_config.dev.yml']
    command: ['jekyll', 'serve', '--watch', '--force_polling']
    environment:
      - JEKYLL_ENV=development
    ports:
        - "4000:4000"
    volumes:
        - ./:/srv/jekyll
