version: '2'

services:

  jekyll-container:
    build: .
    # image: "jekyll/jekyll:latest"
    command: jekyll serve --watch --force_polling
    ports:
        - "4000:4000"
    volumes:
        # - ./:/app
        - ./:/srv/jekyll
